POST http://localhost:3000/products
Content-Type: application/json

{
    "title": "HP",
    "price": 299,
    "description": "Great job!"
}

###
GET http://localhost:3000/products

###
GET http://localhost:3000/products/0.98622279686549294444444

###
PUT http://localhost:3000/products/0.8805548995552908
Content-Type: application/json

{
    "price": 499
}

###
DELETE http://localhost:3000/products/2222222